### ISSUE TITLE
Bootstrap taking close to 10 mins through Unattended install

### ISSUE THREAD

**Issue by raghuteja9** [chef/ohai#1041]
## Description

We are trying to bootstrap nodes in our environment with our Chef Server and doing it through Unattended installation. When we are bootstrapping it , its taking close to 10 mins. When I enabled the debug mode and looked at the Logs, I saw that the IpScopes Plugin and the Filesystem plugin were taking close to 9 mins. When i Disabled the Filesystem Plugin, it is taking 4 mins. What if we want the Filesystem data in the future. 

## Ohai Version

Ohai: 8.23.0

## Platform Version

Red Hat Enterprise Linux Server release 6.9 

## Ohai Output

the Bootstrap log is here 
https://gist.github.com/raghuteja9/2f86769cedcd0337a2e1045fa2ca9720

**Comment by raghuteja9** [comment]
Hi Team, 

Can anyone look into this or has it been resolved in any of the recent releases?

**Comment by thommay** [comment]
@raghuteja9 there's not anything we can reasonably do here - your log reveals that the df commands that ohai runs are taking a long time to complete. If you don't use the filesystem plugin, then you should turn it off, but I would investigate the commands that ohai runs:
 * `df -P`
 * `df -iP`
 * `mount`
 * `lsblk -n -P -o NAME,UUID,LABEL,FSTYPE`
 * `blkid`

and figure out which one is slow and why. Typically this is caused by malfunctioning network mounts.

**Comment by tas50** [comment]
@raghuteja9 It also might be worth giving Chef 13 a try as that ships with Ohai 13. In Ohai 13 we removed our existing filesystem plugin and now use only what was know as Filesystem2 in the version of Ohai that you are on. That change *should* significantly reduce the number of calls being made to filesystem utilities.
