### ISSUE TITLE
ipmi module not loaded

### ISSUE THREAD

**Issue by mrhopeman** [chef/ohai#1245]
## Description

node['ipmi']['channels'] is not defined, because the ipmi module(s) are not loaded. To execute `modprobe ipmi_devintf` and `modprobe ipmi_si` solve this issue, but this can not be executed in a cookbook, because ohai loads all informations before the cookbooks are converged.
Also the ohai debug log shows, that loading the modules returned 1

## Ohai Version

Ohai: 8.24.1

## Platform Version

Ubuntu 16.04

## Ohai Output

`
[2018-09-10T08:31:43+00:00] DEBUG: Loading plugin at /etc/chef/ohai/plugins/ipmi.rb
[2018-09-10T08:31:44+00:00] DEBUG: Plugin Ipmi: ran 'modprobe impi_si impi_devintf' and returned 1
[2018-09-10T08:31:44+00:00] DEBUG: Plugin Ipmi: ran 'ipmitool channel info' and returned 1
`

**Comment by tas50** [comment]
This is a bit tricky since we don't want to modify the state of the system when running ohai. If the module isn't loaded we assume the user wants it that way. What you could do to make this work is use the kernel_module resource in Chef 14 to load the module and then use a notify from that resource to the ohai resource to force the values to reload. You could also just load the ipmi modules as part of a bootstrapping process so you can ensure they're loaded.
