### ISSUE TITLE
Ohai Identification of Hyper-V Hypervisor

### ISSUE THREAD

**Issue by Azrael808** [chef/ohai#647]
I am attempting to identify when a Chef client is running as a Hyper-V guest, but the ohai attributes currently identify the Hypervisor as "virtualpc".

It's not a show-stopper, as I've just matched that `node['virtualization']['system']` attribute value in my recipes for now, but I did notice there was an existing Jira ticket for this and I wondered if a fix was on the roadmap?

https://tickets.opscode.com/browse/OHAI-43

**Comment by btm** [comment]
You're on a linux system running under hyperv?

http://blogs.technet.com/b/tonyso/archive/2009/08/20/hyper-v-how-to-detect-if-you-are-inside-a-vm.aspx

That indicates that the motherboard version should indicate the version of HyperV. I wonder what it returns on VirtualPC.

FWIW, on my virtual box guest the baseboard information is:
```
wmic:root\cli>baseboard get manufacturer, product, serialnumber,version
Manufacturer        Product     SerialNumber  Version
Oracle Corporation  VirtualBox  0             1.2
```

It looks like we're currently looking at wmi information in `lib\ohai\plugins\windows\virtualization.rb` so it wouldn't be that hard to detect HyperV + Virtualbox on Windows guests.

**Comment by mwrock** [comment]
On a Hyper-V guest the above `wmic` call yields:

```
Manufacturer           Product          SerialNumber                      Version
Microsoft Corporation  Virtual Machine  8634-3476-0293-6971-8209-0110-05  7.0
```

**Comment by Azrael808** [comment]
@btm yes, I am running a Linux guest under Hyper-V... Not through choice you understand, but a business partner is using it internally!

If it helps, I can attach the output of `dmidecode`?

**Comment by btm** [comment]
@Azrael808 yeah, dmidecode and the version of hyper-v would be good. I think we need to figure out when virtual-pc became hyper-v.

https://en.wikipedia.org/wiki/Windows_Virtual_PC
```
Release dates of Microsoft Virtual PC 2007
Date	    Version	Description
2006-10-11	6.0.122	Beta
2007-01-02	6.0.142	Release Candidate 1
2007-02-22	6.0.156	Release to Manufacturing
2008-05-15	6.0.192	Service Pack 1[13]
2009-02-20	6.0.210	Update[14]
2009-07-14	N/A	Security Update MS09-33[15]
```

Then "Windows Virtual PC" (instead of "Microsoft Virtual PC") was version 6.1. From @mwrock's post, it looks like Hyper-V got version 7. So if we really want to return hyperv instead of virtualpc, we should do so when version >= 7. 

It's a bit of a breaking change though. I'm sure a bunch of people have already worked around it like you have.

**Comment by mwrock** [comment]
version 7 of Hyper-V is the new version released with the latest November update of win 10 and TP 4 of server 2016. I found this chart here that has a chronology of Hyper-V versions: http://windowsitpro.com/hyper-v/hyper-v-vm-versions-server-os

Here is `dmidecode` output from an ubuntu Hyper-V guest:
```
System Information
        Manufacturer: Microsoft Corporation
        Product Name: Virtual Machine
        Version: 7.0
        Serial Number: 9242-2608-7031-8934-2088-5216-61
        UUID: C2431A2D-D69C-244F-9DE8-CD5D09E0DA39
        Wake-up Type: Power Switch

Handle 0x0002, DMI type 2, 8 bytes
Base Board Information
        Manufacturer: Microsoft Corporation
        Product Name: Virtual Machine
        Version: 7.0
        Serial Number: 9242-2608-7031-8934-2088-5216-61
```
It seems like ohai goes wrong here: https://github.com/chef/ohai/blob/0e6456ca3e56ae4e84feabff87f3c538bf38964a/lib/ohai/plugins/linux/virtualization.rb#L121

It is marking the Virtualization as VirtualPC if the manufacturer is microsoft. While its a nice shout out to days of yore, its been incorrect for a while.

**Comment by Azrael808** [comment]
Right, here's the output from `dmidecode`:

[dmidecode.txt](https://github.com/chef/ohai/files/44081/dmidecode.txt)

The partner tells me that this is HyperV running on Windows Server 2012 R2.

**Comment by tas50** [comment]
I'm working on cleaning up the dmidecode logic on both Linux and FreeBSD and I figure while I'm there we should clean up the VirtualPC vs. Virtual Server vs. Hyper-V logic.  We seem to have decided that version 7.0 is Hyper-V, but it also seems like we could just search for the Hyper-V string since the BIOS version is "Hyper-V UEFI Release v1.0".  VirtualPC is where I get a bit confused.  Version 6 is VirtualPC, but I'm also seeing mention around the Internet (and in our tests) that version VS2005R2 is also VirtualPC.  Finally there's Virtual Server 2005, which interestingly enough isn't version VS2005R2, but instead seems to be version 5.0.  Is there anyone out there that can confirm that older versions of VirtualPC are version VS2005R2 and VirtualServer are version 5.0?

**Comment by tas50** [comment]
Something like this:
      when /Manufacturer: Microsoft/
        if dmi_data =~ /Product Name: Virtual Machine/
          if dmi_data =~ /Version: (VS2005R2|6.0)/
            return 'virtualpc'
          elsif dmi_data =~ /Version: (7.0|Hyper-V)/
            return 'hyperv'
          elsif dmi_data =~ /Version: 5.0/
            return 'virtualserver'
          end

**Comment by tas50** [comment]
I'm also working to improve our detection of Azure hosts and avoid detecting nodes as being on Hyperv once we detect them as running on Azure.

**Comment by tas50** [comment]
@Azrael808 What distro / release is that dmidecode data from?

**Comment by tas50** [comment]
We should be properly detecting Hyper-V with the merge of #647.  I have some additional work to distinguish between Hyper-V and Azure, but for now both Hyper-V and Azure will show up at Hyper-V guests.

**Comment by Azrael808** [comment]
@tas50 it's a CentOS 7 VM.
