### ISSUE TITLE
ohai/lib/ohai/mixin/gce_metadata.rb does dns lookup for metadata.google.internal

### ISSUE THREAD

**Issue by ZeroChaos-** [chef/ohai#849]
Is it intentional that this mixin seems to do a dns lookup all the time?  Is there no way to detect if this is a google cloud service machine before making this dns lookup?

**Comment by tas50** [comment]
We do the DNS lookup because that works 100% of the time. If we had the chance to do it all over again we would have done our best to detect things and required a hint file for 100% reliable detection. Unfortunately if we move to that method at this point we'll break many users that rely on the 100% reliable detection that is DNS lookups. It's less than ideal and certainly not something we'd do if we had the opportunity to do it all over again.
