### ISSUE TITLE
make a required/critical plugins list

### ISSUE THREAD

**Issue by jaymzh** [chef/ohai#879]
## Description

(perhaps this should be an RFC... if so, let me know and I'll write one).

It would be really nice if we could have a list of plugins that are required. We currently have a resource early on in our run that checks for `node[:fqdn]`, `node[:filesystem2]`, etc. - and apparently @coderanger  does as well.

Why not have an `ohai.config[:required_plugins]` where if those plugins fail, Ohai `abort`s and causes the chef run to fail. This list can be empty by default preserving compatibility.
## Ohai Version

N/A
## Platform Version

N/A
## Ohai Output

N/A

**Comment by mcquin** [comment]
This is very similar to an idea that we did not have a chance to implement with Ohai 7. I like the concept of being able to configure this for your specific needs, rather than a fixed list.

Regarding a need for an RFC, this is probably a small enough change (code-wise) that it probably doesn't need one. However, there are few (intentional) errors raised by plugins, if any, which cause Ohai to terminate a Chef run. Which means you may need to modify chef to get this to work. If that's the case, I think you would need to create an RFC since it touches multiple projects and will require some release orchestration.

I'm just going off [When should I submit an RFC](https://github.com/chef/chef-rfc/blob/master/rfc000-rfc-process.md#when-should-i-submit-an-rfc).

**Comment by mcquin** [comment]
If you wanted to propose a list of always required plugins, then I'd definitely say RFC.

**Comment by tas50** [comment]
It seems like a list of core plugins would be handy to have. Fun fact: we added 10 new plugins in the last year. We have a lot of them now.
